apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: efv-ui
  labels:
    app: efv-ui
    app.kubernetes.io/name: efv-ui
    app.kubernetes.io/component: frontend
spec:
  lookupPolicy:
    local: false
